export const SCREEN_CONFIGURATIONS = {
  main: [
    { name: "index" },
    { name: "+not-found" },
    { name: "account-blocked" },
    { name: "account-deleted" },
  ],
  onboarding: [
    { name: "onboard/introduction", title: "Inducción" },
    { name: "onboard/harvest-criteria", title: "Criterios de Cosecha" },
    { name: "onboard/internal-formation", title: "Formación Interna" },
    { name: "onboard/cluster-classification", title: "Clasificación de racimos" },
  ],
  auth: [
    { name: "auth/login", title: "Iniciar sesión" },
    { name: "auth/login-loading" },
    { name: "auth/profile-selection", title: "Seleccionar perfil" },
    { name: "auth/welcome", title: "Bienvenido" },
  ],
  plantWork: [
    { name: "plant-work/index", title: "Inicio" },
    { name: "plant-work/uploads", title: "Sessiones de Carga" },
    { name: "plant-work/work-flow/overall-summary", title: "Resumen Racimos" },
    { name: "plant-work/work-flow/overall-summary-review", title: "Resumen Racimos" },
    { name: "plant-work/work-flow/end" },
    { name: "plant-work/work-flow/harvest-criteria", title: "Criterios de Cosecha" },
    { name: "plant-work/work-flow/harvest-criteria-tutorial", title: "Criterios de Cosecha" },
    { name: "plant-work/work-flow/harvest-origin", title: "Origen de Cosecha" },
    { name: "plant-work/work-flow/qr-code-option", title: "Opción Código QR" },
    { name: "plant-work/work-flow/qr-code-scanner", title: "Escáner QR" },
    { name: "plant-work/work-flow/report-generation-results" },
    { name: "plant-work/work-flow/report-generation" },
    { name: "plant-work/work-flow/saving-classification" },
    { name: "plant-work/work-flow/provider-selector", title: "Seleccionar Proveedor" },
    { name: "plant-work/work-flow/entry-form", title: "Formulario de Entrada" },
    { name: "plant-work/work-flow/fruit-origin-selector", title: "Formulario de Entrada" },
  ],
  externalClassification: [
    { name: "plant-work/work-flow/external/classification-intro" },
    { name: "plant-work/work-flow/external/classification-result", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/classification-review", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/classification-tutorial", title: "Clasificación de clases" },
    { name: "plant-work/work-flow/external/classification" },
    { name: "plant-work/work-flow/external/detection-feedback", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/detection" },
    { name: "plant-work/work-flow/external/overview", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/picture", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/steps", title: "Clasificación Externa" },
    { name: "plant-work/work-flow/external/tutorial", title: "Clasificación Externa" },
  ],
  internalClassification: [
    { name: "plant-work/work-flow/internal/classification-intro" },
    { name: "plant-work/work-flow/internal/classification" },
    { name: "plant-work/work-flow/internal/classification-tutorial", title: "Clasificación de tipos" },
    { name: "plant-work/work-flow/internal/classification-result", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/classification-review", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/detection" },
    { name: "plant-work/work-flow/internal/detection-feedback", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/overview", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/picture", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/preview", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/steps", title: "Clasificación Interna" },
    { name: "plant-work/work-flow/internal/tutorial", title: "Clasificación Interna" },
  ],
};