export const SCREEN_CONFIGURATIONS = {
  main: [
    { name: "index" },
    { name: "account-blocked" },
    { name: "account-deleted" },
    { name: "+not-found" },
  ],
  onboarding: [
    { name: "onboard/introduction", title: "Inducción" },
    { name: "onboard/harvest-criteria", title: "Criterios de Cosecha" },
    { name: "onboard/internal-formation", title: "Formación Interna" },
    { name: "onboard/cluster-classification", title: "Clasificación de racimos" },
  ],
  auth: [
    { name: "auth/login", title: "Iniciar sesión" },
    { name: "auth/login-loading" },
    { name: "auth/profile-selection", title: "Seleccionar perfil" },
    { name: "auth/welcome", title: "Bienvenido" },
  ],
  fieldWork: [
    { name: "field-work/home", title: "Inicio" },
    { name: "field-work/reports", title: "Reportes" },
    // Flujo de trabajo principal
    { name: "field-work/(work-flow)/overall-summary", title: "Resumen Racimos" },
    { name: "field-work/(work-flow)/cluster-summary", title: "Resumen Racimo" },
    { name: "field-work/(work-flow)/confirm-center" },
    { name: "field-work/(work-flow)/confirm-lot" },
    { name: "field-work/(work-flow)/end" },
    { name: "field-work/(work-flow)/harvest-criteria", title: "Criterios de Cosecha" },
    { name: "field-work/(work-flow)/index", title: "Formulario de entrada" },
    { name: "field-work/(work-flow)/report-generation-results" },
    { name: "field-work/(work-flow)/report-generation" },
    { name: "field-work/(work-flow)/saving-classification" },
  ],
  externalClassification: [
    { name: "field-work/(work-flow)/(external)/classification-intro" },
    { name: "field-work/(work-flow)/(external)/classification" },
    { name: "field-work/(work-flow)/(external)/classification-tutorial", title: "Clasificación de clases" },
    { name: "field-work/(work-flow)/(external)/classification-result", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/classification-review", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/detection" },
    { name: "field-work/(work-flow)/(external)/detection-feedback", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/overview", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/picture", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/preview", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/steps", title: "Clasificación Externa" },
    { name: "field-work/(work-flow)/(external)/tutorial", title: "Clasificación Externa" },
  ],
  internalClassification: [
    { name: "field-work/(work-flow)/(internal)/classification-intro" },
    { name: "field-work/(work-flow)/(internal)/classification" },
    { name: "field-work/(work-flow)/(internal)/classification-tutorial", title: "Clasificación de tipos" },
    { name: "field-work/(work-flow)/(internal)/classification-result", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/classification-review", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/detection" },
    { name: "field-work/(work-flow)/(internal)/detection-feedback", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/overview", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/picture", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/preview", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/steps", title: "Clasificación Interna" },
    { name: "field-work/(work-flow)/(internal)/tutorial", title: "Clasificación Interna" },
  ],
};
